### PR TITLE
Pass proxy certificates to TLS query

### PR DESCRIPTION
**Pull request by ArturAralin**
Reason: some services uses self-signed certificates for communication (or authorization), but currently certs passed only to proxy server not to target service.

Solution: pass certificates to tls query to target service

### CODE REVIEW

**Comment by LuizFelipeNeves** [comment]
Please merge!

**Comment by cupofjoakim** [comment]
@TooTallNate Mind giving this a look? Would help a lot!

**Comment by pauldraper** [comment]
This would have saved me hours.

**Comment by FrankEssenberger** [comment]
I also had the problem the client certificate auth did not work via the proxy agent. I added the proposed manually to our node_modules and it did the trick that the certificate are also forwarded to the target system. Would be nice to get this in the main code line.

**Comment by barroudjo** [comment]
Yep I agree this would be a great addition. We actually need this in our team !

**Comment by dscalzi** [comment]
workaround while this is being ignored: https://github.com/TooTallNate/node-https-proxy-agent/issues/89

**Comment by dscalzi** [comment]
@TooTallNate bump? Libraries like https://github.com/delvedor/hpagent support this out of the box.

**Comment by TooTallNate** [comment]
You should be passing in options meant for the destination endpoint directly to `https.get()`. The options passed in the Agent constructor are meant for the connection to the proxy server.

**Comment by pmuellr** [comment]
For folks following the various TLS threads here ...

I'm in a sticky wicket here ... I'm using `axios`, but it doesn't seem to have a way to send https config along with a request.  The way I've seen it done there is by using a customized http agent.  And we're using the `https-proxy-agent` as our agent, which doesn't seem to support setting https options for the target, just the proxy.

Torn between using `hpagent`, the subclass trick with `callback`, or see if I can chain multiple agents - I guess I want an ordinary https agent, which then chains to the proxy agent, but no idea if this is supported, or will cause other issues ...

**Pull request closed without merging**
