### PR TITLE
[https-proxy-agent] Slice the headers when parsing proxy server response

### PR DESCRIPTION
**Pull request by byjrack**
I have not done heavy testing, but has not broken yet.  Hopefully meets the need.

### CODE REVIEW

**Comment by byjrack** [comment]
Will do, hopefully they meet the need, but up for suggestions if not as I am treading into a bit of new territory.

**Comment by TooTallNate** [comment]
For the changeset, just run `pnpm exec changeset` at the root of the repo and follow the prompts. Select `https-proxy-agent` as the package being updated and "patch" since this is a bug fix. Commit and push the file that gets generated.

As for the test, just apply this change to the `proxy` module to get the existing tests in `https-proxy-agent` to start failing with the issue you are facing:

```diff
diff --git a/packages/proxy/src/proxy.ts b/packages/proxy/src/proxy.ts
index 4a81516..1c2d55d 100644
--- a/packages/proxy/src/proxy.ts
+++ b/packages/proxy/src/proxy.ts
@@ -462,5 +462,5 @@ function requestAuthorization(
                'Proxy-Authenticate': 'Basic realm="' + realm + '"',
        };
        res.writeHead(407, headers);
-       res.end();
+       res.end('Proxy authorization required');
 }
```

**Comment by byjrack** [comment]
Thanks.  Yeah did an npx changeset and it seemed to assume a major so I need to clean that up before I push it upstream.  And good call on adding the text to the return as that is an easy tweak to add a content body and generate the error if it's not checked.

**Review by TooTallNate — APPROVED** [review]
Looking great now, thank you!

**Comment by byjrack** [comment]
Thanks for the assist on the patch as I am a bit rusty. 😅

**Pull request merged**
